### ISSUE TITLE
Uncheck all doesn't update

### ISSUE THREAD

**Issue by dannydinges** [fourstacks/nova-checkboxes#1]
I have this implemented with a nullable field and when I check some options and save the resource it works well. Then if I go back and uncheck all the boxes and save the resource doesn't update. Says it's successful but the boxes are still checked.

**Comment by fourstacks** [comment]
Hi @dannydinges.  Yep, I've now replicated this locally.  Will push up a fix for this later today.  Thanks for the report

**Comment by fourstacks** [comment]
@dannydinges - this should now be resolved in the latest version ([v0.0.5](https://github.com/fourstacks/nova-checkboxes/releases/tag/v0.0.5))

**Comment by dannydinges** [comment]
Thanks! Appreciate the quick fix.
