### ISSUE TITLE
Select all/Deselect all

### ISSUE THREAD

**Issue by niladam** [fourstacks/nova-checkboxes#11]
Any plans on providing an option to select/deselect all ?

**Comment by fourstacks** [comment]
@niladam - sorry for such a slow reply.  No immediate plans for this though it is a nice idea.  Will give it some thought and if it's an easy win then I'll add it to the package.

**Comment by lenvanessen** [comment]
Hi,

Just wanted to let you know that we're looking for exactly the same functionality! So if you want to revisit this descision that would be great

**Comment by gkermer** [comment]
I would appreciate this feature, too!
