### ISSUE TITLE
How to do localization?

### ISSUE THREAD

**Issue by KnowledgeWanderer** [fourstacks/nova-checkboxes#19]
I tried this
```
Checkboxes::make(trans('nova.amenities'), 'amenities', Amenity::class)
                ->options(\App\Amenity::all()->pluck('name'))
                ->columns(2),
```
which works on other relationships, but can't get it work even if I try other variances. 
Any clue to how do I do this? Thank, love.

**Comment by KnowledgeWanderer** [comment]
@fourstacks help please

**Comment by fourstacks** [comment]
`\App\Amenity::all()->pluck('name')` should probably be:

`\App\Amenity::all()->pluck('name')->all()`

`pluck()` returns a collection and the `options` method is expecting an array

**Comment by KnowledgeWanderer** [comment]
did this and I get array to string conversion
```
Checkboxes::make(trans('pbadmin.amenities'), Amenity::class)
                ->options(\App\Amenity::all()->pluck('name')->all())
                ->columns(2)
```
my problem is not that I don't get the values, that works, the problem is that the make() method of your class doesn't seem to accept localization or I may be doing it wrong

If I do this
```
Checkboxes::make(trans('pbadmin.amenities'), 'Amenities')
                ->options(\App\Amenity::all()->pluck('name')->all())
                ->columns(2),
```
then there are simply no values being saved, so the pluck thing works and it returns an array because I'm doing a cast as array in the RealEstate Model

**Comment by KnowledgeWanderer** [comment]
@fourstacks can you give me some insights on this? really have to translate this field and I'm not having success studying your method.
