### ISSUE TITLE
Using integers as values won't correctly store and load the selected options

### ISSUE THREAD

**Issue by andypa** [fourstacks/nova-checkboxes#2]
Nova Version: 1.0.12
nova-checkboxes version: 0.0.6
How to reproduce:
Use following options array:

```
Checkboxes::make('Your Field')->options([
                1 => 'Option 1',
                2 => 'Option 2',
                3 => 'Option 3',
])->hideFromIndex(),
```

Now edit this field, select some options and try to "Update & Continue editing". On my end, the selected values won't be correctly loaded. If you need any further info, please let me know :)

**Comment by fourstacks** [comment]
Hi @andypa - I've replicated this problem and I know what's causing it.  Will try and sort a fix for you tomorrow

**Comment by fourstacks** [comment]
@andypa @bradders

I've refactored the field fairly significantly under the hood and it should now support the use of integers as your option keys. 

Give v0.1.0 a whirl and let me know how you get on.

**Comment by andypa** [comment]
@fourstacks wow, very sweet, thank you for the quick fix! I will test it on Monday and will let you know 👍
