### ISSUE TITLE
Spacing on form not working Nova 2.6.1

### ISSUE THREAD

**Issue by mikecornille** [fourstacks/nova-checkboxes#22]
![Screen Shot 2019-11-08 at 11 30 09 AM](https://user-images.githubusercontent.com/4032373/68497914-354f8d80-021b-11ea-99ad-516049701c41.png)

Was working with nova 2.0 then I upgraded to nova 2.6.1 and the spacing was lost, do I need to do anything to get spacing back to normal?

**Comment by sdmpxs** [comment]
I can confirm this.

**Comment by fourstacks** [comment]
Fixed in v0.1.6
