### ISSUE TITLE
Save checkbox array to pivot table

### ISSUE THREAD

**Issue by djphaser** [fourstacks/nova-checkboxes#26]
Hello,

can you please help me how to save an array to a pivot table? In the documentation, you write that the value is stored in one field in the table. Please try to give an example, or refer me to an example on the Internet. I am a beginner and this is not clear to me. Thank you.

**Comment by blomdahldaniel** [comment]
Hey! If you are looking for the possibility to use checkboxes for Laravel relationships this is a perfect guide for how to do it!

https://ivanmijatovic.com/laravel-nova-belongstomany-relationship-as-checkbox
