### ISSUE TITLE
Checkboxes don't work in Nova Actions since nova v3.11.1

### ISSUE THREAD

**Issue by wjstraver** [fourstacks/nova-checkboxes#29]
I've updated my project to Nova v3.11.1 and since then this checkboxes plugin does not work anymore in Nova Action fields. 

In the popup when I select some of the checkboxes, these values are not being sent to the backend on the ajax request.

Example Code:

```php
use Fourstacks\NovaCheckboxes\Checkboxes;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\Text;

class MyAction extends Action
{
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function handle(ActionFields $fields, Collection $invitees): array
    {
        //...
    }

    public function fields(): array
    {
        return [
            Text::make('Text'),
            Checkboxes::make('boxes')->options([
                'value_1' => 'Value 1',
                'value_2' => 'Value 2'
            ]),
            Select::make('Select')->options([
                1 => 'Option',
                2 => 'Option 2'
            ])
                ->displayUsingLabels(),
        ];
    }
}
```

Result:
![Screenshot 2020-10-14 at 15 43 29](https://user-images.githubusercontent.com/11840660/95998560-48101080-0e35-11eb-86b9-d6ced92dee8a.png)

![Screenshot 2020-10-14 at 15 43 54](https://user-images.githubusercontent.com/11840660/95998635-59f1b380-0e35-11eb-8a79-69a9fbf589fc.png)

**Comment by fourstacks** [comment]
Hi @wjstraver - sorry to hear you're having issues.  I'm afraid I don't really use this field in any projects any more and I'm pushed for time to make updates.  I'd totally accept a PR to fix this however.
