### ISSUE TITLE
Work with epartment/nova-dependency-container

### ISSUE THREAD

**Issue by fukumori** [fourstacks/nova-checkboxes#4]
I need make nova-checkboxes work with nova-dependency-container on a specific checkbox.

Could you help me?

**Comment by ferrl** [comment]
I believe you should open this issue in the other package, since the show/hide logic is there.

**Comment by fourstacks** [comment]
Closing this as it's likely to be more an issue in the other package.  Feel free to reopen if that proves not to be the case

**Comment by shradhabanerjee** [comment]
@lfukumori , Were you able to have the checkboxes working with nova-dependency-container ? If yes what was the solution.
Thanks !
