### ISSUE TITLE
Rules not validated correctly

### ISSUE THREAD

**Issue by XGhozt** [fourstacks/nova-checkboxes#6]
I just tried to add `creationRules('required')` and it doesn't appear to be working. It turns the fields red if there are also other required fields but I can still submit it with nothing selected without any error.

**Comment by fourstacks** [comment]
@XGhozt - to be honest I've not really tried this field out with any validation rules yet.  Will give that a whirl and see if I can track down where the issue is

**Comment by batFormat** [comment]
@fourstacks you have not watched it?

**Comment by ngiraud** [comment]
@XGhozt You can just use a custom clusure rule which will check for a true value in the json like this :

```
->rules('required', 'json', function($attribute, $value, $fail) {
    if (!collect(json_decode($value, true))->containsStrict(true)) {
        return $fail('The '.$attribute.' field is invalid.');
    }
})
```
