### ISSUE TITLE
Group posibility

### ISSUE THREAD

**Issue by niladam** [fourstacks/nova-checkboxes#9]
Are there any plans to provide an option of grouping these into their own categories ?

For example you could have a GROUP of fields and that would save to `column.group` in JSON..

**Comment by fourstacks** [comment]
@niladam - sorry for such a slow reply.  You can achieve something along the lines of what you've described already by using Json notation in your attribute names:

```
Checkboxes::make('Group One', 'categories->group_1')
    ->options([
      1 => 'Option 1',
      2 => 'Option 2',
      3 => 'Option 3'
   ])
   ->saveUncheckedValues(),

Checkboxes::make('Group Two', 'categories->group_2')
   ->options([
      1 => 'Option 1',
      2 => 'Option 2',
      3 => 'Option 3'
   ])
   ->saveUncheckedValues(),
```

This would result in a structure similar to this in your DB field:

`{"group_1":{"1":true,"2":false,"3":true},"group_2":{"1":false,"2":true,"3":false}}`
